### ISSUE TITLE
main.db/LOCK: No such file

### ISSUE THREAD

**Issue by jtagcat** [kdrag0n/pyrobud#366]
I tried creating the directory, and on an another try, the file, no change in the output.

```
$ docker run --rm -itv "/home/jc/de/pyrobud:/data" kdrag0n/pyrobud
  INFO     | launch  | Loading code...
  INFO     | launch  | Loading config
  INFO     | launch  | Initializing Sentry error reporting
  INFO     | launch  | Using uvloop event loop
  INFO     | launch  | Initializing bot
  ERROR    | asyncio | Task exception was never retrieved
future: <Task finished name='Task-2' coro=<run.<locals>.new_coro() done, defined at /opt/venv/lib/python3.8/site-packages/aiorun.py:202> exception=Error(b'NotFound: main.db/LOCK: No such file
or directory')>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/aiorun.py", line 212, in new_coro
    await coro
  File "/opt/venv/lib/python3.8/site-packages/pyrobud/core/bot.py", line 50, in create_and_run
    bot = cls(config)
  File "/opt/venv/lib/python3.8/site-packages/pyrobud/core/bot.py", line 35, in __init__
    super().__init__()
  File "/opt/venv/lib/python3.8/site-packages/pyrobud/core/telegram_bot.py", line 47, in __init__
    super().__init__(**kwargs)
  File "/opt/venv/lib/python3.8/site-packages/pyrobud/core/module_extender.py", line 22, in __init__
    super().__init__(**kwargs)
  File "/opt/venv/lib/python3.8/site-packages/pyrobud/core/command_dispatcher.py", line 21, in __init__
    super().__init__(**kwargs)
  File "/opt/venv/lib/python3.8/site-packages/pyrobud/core/database_provider.py", line 21, in __init__
    self._init_db(db_path)
  File "/opt/venv/lib/python3.8/site-packages/pyrobud/core/database_provider.py", line 41, in _init_db
    plyvel.DB(db_path, create_if_missing=True, paranoid_checks=True)
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 94, in plyvel._plyvel.raise_for_status
plyvel._plyvel.Error: b'NotFound: main.db/LOCK: No such file or directory'
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
$
```

**Comment by kdrag0n** [comment]
This is caused by permission issues. Make sure the pyrobud user inside the container has permission to write to your data directory.
